# Generated by Django 4.0 on 2022-01-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_bus_routes_payment_feedback_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes',
            name='bSeats',
            field=models.IntegerField(default=0),
        ),
    ]
